/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tools_zhang_com_jnilibrary_NdkUtils */

#ifndef _Included_tools_zhang_com_jnilibrary_NdkUtils
#define _Included_tools_zhang_com_jnilibrary_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tools_zhang_com_jnilibrary_NdkUtils
 * Method:    fromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tools_zhang_com_jnilibrary_NdkUtils_fromJni
  (JNIEnv *, jclass);

/*
 * Class:     tools_zhang_com_jnilibrary_NdkUtils
 * Method:    getNormalJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tools_zhang_com_jnilibrary_NdkUtils_getNormalJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
